SRC += src/cadical/analyze.cpp \
       src/cadical/arena.cpp \
       src/cadical/assume.cpp \
       src/cadical/averages.cpp \
       src/cadical/backward.cpp \
       src/cadical/backtrack.cpp \
       src/cadical/bins.cpp \
       src/cadical/block.cpp \
       src/cadical/ccadical.cpp \
       src/cadical/checker.cpp \
       src/cadical/clause.cpp \
       src/cadical/collect.cpp \
       src/cadical/compact.cpp \
       src/cadical/condition.cpp \
       src/cadical/config.cpp \
       src/cadical/constrain.cpp \
       src/cadical/contract.cpp \
       src/cadical/cover.cpp \
       src/cadical/decide.cpp \
       src/cadical/decompose.cpp \
       src/cadical/deduplicate.cpp \
       src/cadical/elim.cpp \
       src/cadical/ema.cpp \
       src/cadical/extend.cpp \
       src/cadical/external.cpp \
       src/cadical/file.cpp \
       src/cadical/flags.cpp \
       src/cadical/format.cpp \
       src/cadical/gates.cpp \
       src/cadical/instantiate.cpp \
       src/cadical/internal.cpp \
       src/cadical/ipasir.cpp \
       src/cadical/limit.cpp \
       src/cadical/logging.cpp \
       src/cadical/lookahead.cpp \
       src/cadical/lucky.cpp \
       src/cadical/message.cpp \
       src/cadical/minimize.cpp \
       src/cadical/mobical.cpp \
       src/cadical/occs.cpp \
       src/cadical/options.cpp \
       src/cadical/parse.cpp \
       src/cadical/phases.cpp \
       src/cadical/probe.cpp \
       src/cadical/profile.cpp \
       src/cadical/proof.cpp \
       src/cadical/propagate.cpp \
       src/cadical/queue.cpp \
       src/cadical/random.cpp \
       src/cadical/reap.cpp \
       src/cadical/reduce.cpp \
       src/cadical/rephase.cpp \
       src/cadical/report.cpp \
       src/cadical/resources.cpp \
       src/cadical/restart.cpp \
       src/cadical/restore.cpp \
       src/cadical/score.cpp \
       src/cadical/shrink.cpp \
       src/cadical/signal.cpp \
       src/cadical/solution.cpp \
       src/cadical/solver.cpp \
       src/cadical/stats.cpp \
       src/cadical/subsume.cpp \
       src/cadical/terminal.cpp \
       src/cadical/ternary.cpp \
       src/cadical/tracer.cpp \
       src/cadical/transred.cpp \
       src/cadical/util.cpp \
       src/cadical/var.cpp \
       src/cadical/version.cpp \
       src/cadical/vivify.cpp \
       src/cadical/walk.cpp \
       src/cadical/watch.cpp
